---
version: "3.4"
services:
  mongodb:
    image: mvertes/alpine-mongo:latest
    networks:
      - mongo
  web:
    build: .
    command: "/wait-for-it.sh mongodb:27017 -- morbo script/app.pl"
    depends_on:
      - mongodb
    networks:
      - mongo
    ports:
      - "3000:3000"
  web-cron:
    build: .
    command: "/wait-for-it.sh mongodb:27017 -- perl cron/update.pl"
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: ${MC_CONF_PRIVATE_DIR:-.}/github-meets-cpan/environment.json
        target: /code/environment.json
        read_only: true
    networks:
      - mongo
networks:
  mongo:
